New Login: Sign Up and Pin Initial Setup
Criptext/Criptext-Email-React-Client pull request #1504
Opened 2020-08-19 19:04 UTC by Hirobreak

2020-10-21 13:52 UTC, danieltigse requested changes

2020-10-21 13:52 UTC, danieltigse commented on electron_app/src/clientManager.js
> +  console.log(params);
remove logs

2020-10-21 13:52 UTC, danieltigse commented on electron_app/src/ipc/login.js
> +  console.log('FORCE CLOSE : ', forceClose);
remove logs

2020-10-21 15:23 UTC, javiteri95 approved these changes

2020-10-22 20:51 UTC, danieltigse approved these changes

2020-10-22 20:52 UTC, merged